### ISSUE TITLE
WebDisplay Mod

### ISSUE THREAD

**Issue by OyunsuzOyuncuTR** [montoyo/webdisplays#103]
I using a WebDisplay Mod but the screen white.(Im Turkish , no good speak english.Sorry)the screen is just white, nothing is coming.
minecraft version 1.12.2

![dosyalar](https://user-images.githubusercontent.com/77536085/104812747-60694000-5815-11eb-99b1-09b5104c0379.png)
![image](https://user-images.githubusercontent.com/77536085/104812852-2d737c00-5816-11eb-8b3b-cc9b56048d93.png)

**Comment by montoyo** [comment]
Dup #102 
Please try with MCEF 1.11b

**Comment by OyunsuzOyuncuTR** [comment]
fixed.thank you

**Comment by sidequestlegend** [comment]
I hate to hijack this issue, but I also have this problem and since its fixed I didnt want to open another issue. I just wanted to ask if i need to build the jar from source or is there somewhere i can download 1.11b ?
