### ISSUE TITLE
When I turn on the display screen it turns on but white, my friend can see it but I can't!

### ISSUE THREAD

**Issue by NFSMW2005** [montoyo/webdisplays#104]
I tried everything but I can't find the files needed to fix this 
![2021-01-18_09 26 20](https://user-images.githubusercontent.com/77635247/104947173-34160680-5970-11eb-98f8-f24a9d132d84.png)

**Comment by ItsK1tty** [comment]
what's your MCEF version?

**Comment by NFSMW2005** [comment]
1.12.2 11.1

**Comment by NFSMW2005** [comment]
> what's your MCEF version?

1.12.2 1.11

**Comment by montoyo** [comment]
> I tried everything

![image](https://user-images.githubusercontent.com/6413436/104961999-6df61400-5a27-11eb-8b89-e93fa2964ae1.png)

Dup #102
