### ISSUE TITLE
wdIsEmitting(x, y) is not returning true or false

### ISSUE THREAD

**Issue by KitomaGithub** [montoyo/webdisplays#105]
wdIsEmitting(x, y) is just returning {"emitting": true/false} not true or false.

this is what I get if Im using wdIsEmitting in my HTML.
![image](https://user-images.githubusercontent.com/22256117/106267658-edc08180-6264-11eb-8615-325ec96d09fb.png)

This is how I used wdIsEmitting:
if(wdIsEmitting(0,7)){
alert("hello");
}

Is there something wrong with my use?

**Comment by montoyo** [comment]
Hi,
A few things:
First, all `wdXXX` functions require a callback, so in order for your code to work you would need to pass a function as the last argument and put your 'if' there:
```js
wdIsEmitting(0, 7, function(emitting) {
    if(emitting) {
        alert("hello");
    }
});
```
Second, `alert` is very unlikely to work in a WebDisplays context.

Regards,
 - montoyo.

**Comment by KitomaGithub** [comment]
> 
> 
> Hi,
> A few things:
> First, all `wdXXX` functions require a callback, so in order for your code to work you would need to pass a function as the last argument and put your 'if' there:
> 
> ```js
> wdIsEmitting(0, 7, function(emitting) {
>     if(emitting) {
>         alert("hello");
>     }
> });
> ```
> 
> Second, `alert` is very unlikely to work in a WebDisplays context.
> 
> Regards,
> 
>     * montoyo.

Ah thx, I understand how to use it now and its working.
Thx for the quick response

**Comment by montoyo** [comment]
No worries!
