### ISSUE TITLE
(Suggestion) Video Player

### ISSUE THREAD

**Issue by JeysRT** [montoyo/webdisplays#108]
@montoyo did you ever thought about using a video player to play mp4/mkv/... formats? You managed to implement chromium in minecraft, what if you can implement vlc or other video player, you could make an extra web display which uses the video player to play the videos on the WD_Filehost for example. Also VLC can play videos from the web.

**Comment by montoyo** [comment]
This would only be a temporary workaround. The real issue is that JCEF should be recompiled specifically for MCEF and this would take a tremendous amount of time which I don't have.

**Comment by JeysRT** [comment]
I think someone compiled it successfully with H.246 / H.256

**Comment by montoyo** [comment]
Yeah I've yet to see that. I remember someone saying he/she did manage to do it but I've never had access to the result...

**Comment by JeysRT** [comment]
Yeah... that's a bit annoying

**Comment by JeysRT** [comment]
I would like to do that but... i'm not familiar with cef
