### ISSUE TITLE
Unable to launch game due to proxy error.

### ISSUE THREAD

**Issue by reiyua** [montoyo/webdisplays#113]
Hello,

Every time I attempt to launch the web displays mod, I get this error:

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: net.montoyo.wd.client.ClientProxy
Exit Code: -1

Is there anything I can do?

**Comment by ItsK1tty** [comment]
Try to redownload the mod.

**Comment by HypeRayy** [comment]
Just tried reinstalling, it still does not work.

**Comment by ItsK1tty** [comment]
It's been a month already. Try removing the config files in the config folder
