### ISSUE TITLE
[1.10.2] Localization problem

### ISSUE THREAD

**Issue by the-nick-dev** [montoyo/webdisplays#12]
You used resource format 3 for localization in 1.10.2, when you should use format 2 - in result it makes your localization not appear at all (In format 2 you should capitalize files in format "en_US.lang"(Format 2) and not "en_us.lang"(Format 3))

**Comment by the-nick-dev** [comment]
![image](https://i.like-man.ga/9Z6kcm.png)

**Comment by montoyo** [comment]
Correct. I'll fix this.
