### ISSUE TITLE
a bug with flans mod

### ISSUE THREAD

**Issue by brockthefox** [montoyo/webdisplays#13]
![2018-04-05_23 07 27](https://user-images.githubusercontent.com/38122451/38403065-b27c7d7a-392e-11e8-828c-71414ed15fd4.png)
there is a bug where the web display block is pink when i have the flans mod

**Comment by NameHumor** [comment]
that's happening with me too!

**Comment by seancrain** [comment]
This bug seems to be corrected with the latest build of Flan's Mod:

[Flan's Mod 5.6 Beta 3](https://github.com/FlansMods/FlansMod/releases/tag/v5.6-beta.3)

This may be a glitch in the Matrix, I'll let you know if it shows up again.

**Comment by seancrain** [comment]
@montoyo This issue has long since stopped with the beta releases of Flan's Mod. You can close this issue.

**Comment by montoyo** [comment]
Allright thanks.
