### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by Komas19** [montoyo/webdisplays#132]
When i press F1 on any WebDisplays item, the game crashes. Here is the crash-log file :
[crash-2021-04-21_10.39.53-client.txt](https://github.com/montoyo/webdisplays/files/6349376/crash-2021-04-21_10.39.53-client.txt)

**Comment by ItsK1tty** [comment]
Seems like the MCEF issue. Try downgrading to MCEF 1.11b, because your compiled 1.20 doesn't seem to behave normally

**Comment by Komas19** [comment]
same issue

**Comment by Komas19** [comment]
i fixed it
