### ISSUE TITLE
White Screen instead of Website (1.12.2)

### ISSUE THREAD

**Issue by RuslanCoolGuy13** [montoyo/webdisplays#136]
When I tried to open any website, it didnt work. It just showed me white screen. I uninstalled the mod, I made a new world, nothing worked. I even tried to customize my firewall and antivirus, no effect.
What should I do?

**Comment by ItsK1tty** [comment]
Tried looking at other issues?

**Comment by RuslanCoolGuy13** [comment]
> Tried looking at other issues?

Yup. I didnt find any answers tho.

**Comment by ItsK1tty** [comment]
https://github.com/montoyo/webdisplays/issues/125#issuecomment-826039328
https://github.com/montoyo/webdisplays/issues/123#issuecomment-793106671

**Comment by RuslanCoolGuy13** [comment]
> [#125 (comment)](https://github.com/montoyo/webdisplays/issues/125#issuecomment-826039328)
> [#123 (comment)](https://github.com/montoyo/webdisplays/issues/123#issuecomment-793106671)

Yeah, that doesnt really work

**Comment by ItsK1tty** [comment]
What are your java, webdisplays and mcef versions?

**Comment by RuslanCoolGuy13** [comment]
> What are your java, webdisplays and mcef versions?

![image](https://user-images.githubusercontent.com/52858394/116804282-13487a00-ab37-11eb-84ea-297885d00e9f.png)
![image](https://user-images.githubusercontent.com/52858394/116804286-1b081e80-ab37-11eb-921d-29af12765b91.png)
![image](https://user-images.githubusercontent.com/52858394/116804306-3410cf80-ab37-11eb-96c5-19a826c81c72.png)

**Comment by RuslanCoolGuy13** [comment]
Oh, forget it. I updated MCEF version and cleared MCEF cache. It started working... Slowly tho.
