### ISSUE TITLE
Not a issue but a suggestion about the synchronize (Maybe this is useless for you)

### ISSUE THREAD

**Issue by Jacky10X** [montoyo/webdisplays#14]
i just think one of the way that you can synchronize the Webdisplay
You can make every Webdisplay has it owns "synchronizer"
And you can stream every screens (maybe you already think about it if you already knew this then sorry i am being stupid) 
However, this may make some server lag (or super lag?)
So you can make this feature optional which you can make it enabled or disabled by user (you can make this feature default is false)
Maybe someone may have a better suggestion about the synchronize during using this mod or you can find a better suggestion during the development

About the bandwidth problem maybe you can find a way to limit the bandwidth per webdisplay screen

(Maybe you can make 2 more option that we can modify by our users: 
 limited the bandwidth feature : default is true
 and the bandwidth limited value: default is up to you)

Also i just found this
https://stackoverflow.com/questions/40051925/how-to-synchronize-the-display-of-two-web-pages-in-separate-browsers
Maybe this can help you ( i think maybe this is very stupid suggestion for you)

**Comment by montoyo** [comment]
Hello,
Thanks for the suggestion. Yes I have already thought about this, and there are two main problems with streaming:
- The first is, as you said, huge server lag. Not only in terms of computing time (you need to compress the video), but also in terms of bandwidth. Imagine 5 1080p screens being sent to 20 people.
- The second is that most Minecraft server are headless, meaning that they are running in some console, without a graphical user interface. Thus, they are not able to render web pages.

The StackOverflow link you gave does unfortunately not apply to the problem of WebDisplays.
