### ISSUE TITLE
[1.12.2] Black Screen

### ISSUE THREAD

**Issue by Sevcon-glitchy** [montoyo/webdisplays#142]
![2021-06-29_17 38 06](https://user-images.githubusercontent.com/78469857/123775482-ff37b380-d900-11eb-88bd-8ee5af0d4dcf.png)
I want to watch and browse the web, but this keeps happening. I put the upgrades and I turned it on and put a link, but it didn't on!!! Help meeeeeeeeeeeeeeeeeeeeee

**Comment by dextonanderson** [comment]
Hi, try my updated fork of the MCEF project here:

https://github.com/Ruinscraft/mcef/releases/tag/1.12.2-1.30

It should fix your issue

**Comment by Sevcon-glitchy** [comment]
Thanks
