### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by MLDKYT** [montoyo/webdisplays#147]
[mcef.zip](https://github.com/montoyo/webdisplays/files/6916889/mcef.zip)
[log.txt](https://github.com/montoyo/webdisplays/files/6916899/log.txt)
OS: Linux Ubuntu 20.04
Minecraft version: 1.12.2

**Comment by ItsK1tty** [comment]
MCEF does not work on Linux

**Comment by MLDKYT** [comment]
I tried on Windows 10, but I still have a white screen

**Comment by ItsK1tty** [comment]
A log would be great to have

**Comment by MLDKYT** [comment]
Here you go https://paste.ee/p/klngd

**Comment by ItsK1tty** [comment]
It appears you've got outdated MCEF. Consider updating to 1.11b

https://montoyo.net/wd3/?modid=MCEF

**Comment by MLDKYT** [comment]
Oh, I used 1.11 because I thought 1.11b is a beta version, I will try it now

**Comment by MLDKYT** [comment]
It works! Thanks
