### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by BubblePlayzTHEREAL** [montoyo/webdisplays#152]
When I install the Mod, It appears as an HTML Document. When I open the HTML it says "nope.avi". How do I fix this?
![image](https://user-images.githubusercontent.com/58344347/133008650-8af9ccdb-fe4b-4dea-94d9-3d40c8b7f61b.png)
![image](https://user-images.githubusercontent.com/58344347/133008670-9659bc48-7176-4933-8557-f022b2998b03.png)

**Comment by ItsK1tty** [comment]
Try downloading from montoyo.net.

**Comment by BubblePlayzTHEREAL** [comment]
I did

**Comment by ItsK1tty** [comment]
You think you did or you actually did?

**Comment by ItsK1tty** [comment]
It just says so. Google "webdisplays" site:montoyo.net" and "mcef site:montoyo.net" and download from the pages in the results

**Comment by BubblePlayzTHEREAL** [comment]
This website?
![image](https://user-images.githubusercontent.com/58344347/133156230-a4d35419-0c4d-40e2-81e1-495f9d9814a3.png)

**Comment by ItsK1tty** [comment]
Yeah

**Comment by BubblePlayzTHEREAL** [comment]
That is where I downloaded the stuff originally.

**Comment by ItsK1tty** [comment]
I will drop you the mod files on Discord later

**Comment by BubblePlayzTHEREAL** [comment]
K, thanks.
