### ISSUE TITLE
white screen issue

### ISSUE THREAD

**Issue by Cipripq** [montoyo/webdisplays#154]
![image_2021-09-28_172852](https://user-images.githubusercontent.com/91550236/135107516-afb4f731-a1cc-4244-852b-360a784ee003.png)

So i wanna play this cool mod, and i am trying to make it work, but i cant. when i turn it on, white screen. i tried to put URL like google or youtube but no succes. i am on windows 10, please help!!!

**Comment by ItsK1tty** [comment]
Ever tried reading other issues?

**Comment by Cipripq** [comment]
> Ever tried reading other issues?

yes, but didnt work

**Comment by ItsK1tty** [comment]
What's your MCEF version?

**Comment by Cipripq** [comment]
![Screenshot 2021-09-29 174434](https://user-images.githubusercontent.com/91550236/135292449-d5a60a8f-6866-4c6f-a661-505fd9c4c158.png)

**Comment by Cipripq** [comment]
> What's your MCEF version?

![](https://user-images.githubusercontent.com/91550236/135292449-d5a60a8f-6866-4c6f-a661-505fd9c4c158.png)

**Comment by ItsK1tty** [comment]
Download latest MCEF, as described in other topics. Current version is 1.11b

**Comment by Cipripq** [comment]
> Download latest MCEF, as described in other topics. Current version is 1.11b

can you please send me aa link?
i am not too sure where i can download

**Comment by ItsK1tty** [comment]
literally first result
https://montoyo.net/wd3/?modid=MCEF![Screenshot_2021-09-29-20-05-53-443_com.google.android.googlequicksearchbox.png](https://user-images.githubusercontent.com/45013913/135316041-e1f27bcb-c244-46e6-8db1-85e7e3b8b91f.png)

**Comment by Cipripq** [comment]
oh

**Comment by Cipripq** [comment]
> literally first result
> 
> [Screenshot_2021-09-29-20-05-53-443_com.google.android.googlequicksearchbox.png](https://user-images.githubusercontent.com/45013913/135316041-e1f27bcb-c244-46e6-8db1-85e7e3b8b91f.png)
> 
> https://montoyo.net/wd3/?modid=MCEF
![Screenshot 2021-09-29 200751](https://user-images.githubusercontent.com/91550236/135316393-a20cfacf-6de4-4069-a191-afde996a1793.png)

what should i select?

**Comment by ItsK1tty** [comment]
Nothing, if you're not on 1.12.2. This bug was solved on 1.11b branch, which is only for 1.12.2.

**Comment by Cipripq** [comment]
> Nothing, if you're not on 1.12.2. This bug was solved on 1.11b branch, which is only for 1.12.2.

Thank you so much! it worked!!!! now i can build my cinema!!!
thanks for your help. I was surprised you didnt lose your mind with me, however, thx!
