### ISSUE TITLE
Game crashes on certain map whenever I place web display block

### ISSUE THREAD

**Issue by Jclau77** [montoyo/webdisplays#17]
I have a map that I tried testing the mod and as soon as I place it down the game crashes other maps it works perfectly but here is the error I am getting.:

The game crashed whilst tesselating block model
The game crashed whilst tesselating block model
Error: java.lang.NullPointerException: Tesselating block model

If you can help me out with this that'll be great!

**Comment by montoyo** [comment]
Hello,

I'll need your logs, this isn't enough. If you don't know where to find them, please read https://montoyo.net/wdwiki/index.php/Main_Page#Where_are_my_log_files.3F

Thanks.
