### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by Jaydenha09** [montoyo/webdisplays#170]
Why I turn on the display screen but white screen?I am using macOS.
![1](https://user-images.githubusercontent.com/98650905/158062546-ffdfa6a0-7565-4dfb-bca6-8f6e9524e891.png)

**Comment by ItsK1tty** [comment]
Hit me on Discord - K1tty#2077, I have what you need but can't share it here

**Comment by Jaydenha09** [comment]
> Hit me on Discord - K1tty#2077, I have what you need but can't share it here

Can you put the file what I need upin this Discord server?
[](https://discord.gg/VNUU4keU)
