### ISSUE TITLE
WebScreen block has no texture.

### ISSUE THREAD

**Issue by NameHumor** [montoyo/webdisplays#18]
![glitchscreen](https://user-images.githubusercontent.com/39032275/39675963-c36dfefe-5127-11e8-9059-7e68d17b838f.PNG) @montoyo The WebScreen block has no texture, but the functionality for the Internet still works and other WebScreen block textures aren't corrupted. I have proof, (see attached image). I have Flans Mod and all of Flans block textures are corrupted. So are they just corrupting eachother, or it's just a general bug that Flans made?? Let me know at my email, applegordo@gmail.com, or just generally respond.

**Comment by montoyo** [comment]
dup #13 , I'll look into it, thanks for reporting.

**Comment by NameHumor** [comment]
@montoyo Also, whenever I place down a Flans block, the game crashes.

**Comment by MrRedstoneA1** [comment]
Yes, I can verify that this is an issue with 1.12.2 Flan's mod. For me though, Flan's mod blocks are stable, have their textures and don't cause crashes. The only issue is that the WebScreen blocks no longer have their texture. If this could be fixed, I would be very happy. I can't get rid of Flan's mod. it's too important and plays a great part in my normal survival gameplay.
