### ISSUE TITLE
WebScreen went client sided/desynced

### ISSUE THREAD

**Issue by Necrosis000** [montoyo/webdisplays#185]
So me and my friend are playing with the WebDisplays mod but there is a problem where we see 2 different things on the WebScreen...

ex: When we are on youtube we see different videos in the recommended,

Please can someone help

**Comment by ItsK1tty** [comment]
There's no solution.

**Comment by Necrosis000** [comment]
uhh so what am I meant to do?

**Comment by ItsK1tty** [comment]
There are many solutions:
A. Don't watch YouTube
B. Watch YouTube, but play only playlists or insert links for each video.
C. Watch YouTube alone

**Comment by Error340GTL** [comment]
well that sucks
