### ISSUE TITLE
Acidentally breaking screen on click

### ISSUE THREAD

**Issue by Schlagbul** [montoyo/webdisplays#189]
Using MCEF 1.1
Using WebDisplays 1.0

When I try to click the screen the screen breaks, by break I mean, part of it is destroyed causing it to shut down, I have already checked and I have permission to click the screen, please help.

And the keyboard is hooked

**Comment by ItsK1tty** [comment]
Are you clicking with right button, or left button?

**Comment by Schlagbul** [comment]
Left

**Comment by ItsK1tty** [comment]
Try right.

**Comment by Schlagbul** [comment]
It now works, but if I wanted to perform the equivalent to a right click, how would I do so?

**Comment by ItsK1tty** [comment]
Simple. You don't.
