### ISSUE TITLE
Doesn't work on multiplayer(in half)

### ISSUE THREAD

**Issue by Blazejou** [montoyo/webdisplays#199]
So i wanted to watch youtube with my friends but when he turned on a video it was like it was complete different screens because he saw other things than me. im on windows 10, is there anyway to fix it ? im on version mcef 1.11b and webdisplay 1.1

**Comment by ItsK1tty** [comment]
nope. no fix.

**Comment by Blazejou** [comment]
ahhhhhh, is there any way the creator will fix this or no

**Comment by ItsK1tty** [comment]
nope
