### ISSUE TITLE
Screen Block issues

### ISSUE THREAD

**Issue by hiddensea** [montoyo/webdisplays#205]
No matter how big I build or what I change in the config file, it always says "Too small, must be 2x2" when my screens look like this:
![2022-09-28_20 22 13](https://user-images.githubusercontent.com/86420177/192870480-c396a448-8ead-4e53-a023-09166648ef4b.png)

Any soloution? (1.12.2 Windows)

**Comment by ItsK1tty** [comment]
You kinda need to fill it with block screens, y'know...
