### ISSUE TITLE
"Playback of Protected content is not enabled" without Widevine plugin

### ISSUE THREAD

**Issue by itsskyballs** [montoyo/webdisplays#213]
i tried spotify in minecraft,i logged in on my spotify account and i got an error says "Playback of Protected content is not enabled"

**Comment by itsskyballs** [comment]
Chromium needs to update to latest version tho

**Comment by ItsK1tty** [comment]
The version of the Chromium does not matter much in this case. Chromium has to be compiled with Widevine support enabled, and this particular build was not built with Widevine on.

**Comment by itsskyballs** [comment]
Not planned and i dont have idea on my issue so thats it
