### ISSUE TITLE
White screen on pojavlauncher

### ISSUE THREAD

**Issue by PythonNoob999** [montoyo/webdisplays#221]
I'm playing Minecraft java 1.12.2 and playing on mobile app called pojavlauncher wich allow android users to play Minecraft java on mobile anyway my problem is the white screen error i typed the link i want to go in the monitor but still
I tried mcef 1.11, 1.11b, 1.33 the 1.11, 1.11b do not work but the 1.33 didn't load Minecraft at all

So if i tried downloading webdisplay + mcef 1.16 or more will it work or the mod just do not work on Android? Before i waste like 2-3 hours trying every solution i see

**Comment by ItsK1tty** [comment]
It does not work.

**Comment by PythonNoob999** [comment]
Thanks

**Comment by itsskyballs** [comment]
unfortunately this is only works on windows device so there's no support for chromium(cef and based off webdisplays) for Linux or macOS,if I did make a linux or android version of webdisplays,I can but I can't compile a file skit for that💀
