### ISSUE TITLE
WebDisplays Whitescreen 1.12.2

### ISSUE THREAD

**Issue by Milixity** [montoyo/webdisplays#225]
I downloaded MCEF and WebDisplays and the screen just gave me a white screen
![image](https://github.com/montoyo/webdisplays/assets/135869127/44e6b636-173b-45d8-b3d6-5baf70867356)
Please help.
Heres my latest log and mods folder.
[mods.zip](https://github.com/montoyo/webdisplays/files/11680719/mods.zip)
https://pastebin.com/hEtPCh2Z

**Comment by Sarocesch** [comment]
Completed ?
please tell me how you fixed it

**Comment by Miki21032013** [comment]
How you fix it?
