### ISSUE TITLE
Can't watch the video, help!

### ISSUE THREAD

**Issue by serega1734** [montoyo/webdisplays#29]
Hello, I'm from Russia, and would like to watch the video in Facebook, Vk, but I write a Flash-Player error, I installed different versions, nothing helps, please tell me how to fix this problem?

**Comment by Billy-Playz** [comment]
Quoting the wiki...

> 
> "Flash?
> 
> No. You shouldn't be using Flash anyway, it has some serious security issues... "

**Comment by montoyo** [comment]
@Billy-Playz answered correctly. Thanks :)
