### ISSUE TITLE
[1.12.2 / 1.0] players see different pages in the browser

### ISSUE THREAD

**Issue by misdocumeno** [montoyo/webdisplays#30]
the bug happens when I try to put a video on youtube, the players don't see the same screen, different videos appear, as if they were different versions of the page, with different recommendations in the feed, as if they were 2 separate pc

It's a dedicated server with forge 14.23.5.2768

server latest logs https://pastebin.com/p4050AN4

**Comment by montoyo** [comment]
Yeah, this is one of the limitations of WebDisplays. I'm afraid there is no solution to this problem. If you want to learn more about this issue, check out https://montoyo.net/wdwiki/index.php/Screen#Multiplayer_synchronization
