### ISSUE TITLE
[1.12.2] white screen 

### ISSUE THREAD

**Issue by LXSN** [montoyo/webdisplays#31]
hi author when i play this mod with macos i just only see the white screen 
i like this mod 
i hoping fix it if is an easy problem

**Comment by riricraft** [comment]
i have this problem but i don't know what can we do.

**Comment by montoyo** [comment]
Need logs. Check out the "Where are my log files?" here https://montoyo.net/wdwiki/index.php/Main_Page#Where_are_my_log_files.3F if you don't know where to find them.

Also dup #20
