### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by riricraft** [montoyo/webdisplays#32]
Hi,
I writte this text for report a bug.
When i put an URL (youtube.com for exemple) the screen is always white.
I don't know what can i do.
Cordially
Richard Rivier

**Comment by montoyo** [comment]
Need logs. Check out the "Where are my log files?" here https://montoyo.net/wdwiki/index.php/Main_Page#Where_are_my_log_files.3F if you don't know where to find them.

**Comment by montoyo** [comment]
Also, dup #20

**Comment by ririwarrior** [comment]
I agree with you but I don't have do anything, i have instal the mod with other mod. But my screen is always white.
riricraft (with an other account)

**Comment by montoyo** [comment]
Give 👏 me 👏 the 👏 logs 👏

**Comment by ririwarrior** [comment]
how ??
