### ISSUE TITLE
Withe screen

### ISSUE THREAD

**Issue by ririwarrior** [montoyo/webdisplays#34]
My log file:
https://drive.google.com/drive/folders/1k08mAvReXB9tbMRhb_oDHlE5sbUFpBHg?usp=sharing

**Comment by montoyo** [comment]
Re-bonjour,
Je vais écrire en Français parce-que je pense que ça sera bien plus simple...

MCEF n'arrive pas a télécharger les ressources dont il a besoin. Il y a peut-être un proxy, antivirus ou pare-feu qui bloque l'accès au site de ressource. Essayez de désactiver l'antivirus ou le pare-feu, au moins le temps qu'il télécharge les ressources dont il a besoin.

**Comment by ririwarrior** [comment]
Re-bonjour je vous remercie et effectivement je suis français. je vais essayer, et je vous tiens au courant.
Merci

**Comment by ririwarrior** [comment]
> 
> 
> Re-bonjour,
> Je vais écrire en Français parce-que je pense que ça sera bien plus simple...
> 
> MCEF n'arrive pas a télécharger les ressources dont il a besoin. Il y a peut-être un proxy, antivirus ou pare-feu qui bloque l'accès au site de ressource. Essayez de désactiver l'antivirus ou le pare-feu, au moins le temps qu'il télécharge les ressources dont il a besoin.

**Comment by ririwarrior** [comment]
> 
> 
> Re-bonjour,
> Je vais écrire en Français parce-que je pense que ça sera bien plus simple...
> 
> MCEF n'arrive pas a télécharger les ressources dont il a besoin. Il y a peut-être un proxy, antivirus ou pare-feu qui bloque l'accès au site de ressource. Essayez de désactiver l'antivirus ou le pare-feu, au moins le temps qu'il télécharge les ressources dont il a besoin.

**Comment by ririwarrior** [comment]
Bonjour, veuillez m'excusez pour tous mes messages je me suis trompé de bouton ^^.
Je ne réussissais pas à désactiver mon antivirus donc j'ai ajouter une exception pour minecraft. Ce que vous m’avez dit de faire marche et je vous en remercie.
Votre mod est super et mon cinéma vous en remercie (minecraft).

Cordiallepment

**Comment by ririwarrior** [comment]
Pourriez vous fermer ce post s'il vous plait? Et encore merci pour votre aide

**Comment by montoyo** [comment]
🙂
