### ISSUE TITLE
Interview with montoyo

### ISSUE THREAD

**Issue by ItsK1tty** [montoyo/webdisplays#41]
Hey, I've tried watching Interstellar with friends, but when I'm heading to my webserver with .mp4 onboard, the screen stays white, and theres no sound or videos
Steps to reproduce:
1.Make a screen
2.Go to http://minecraft.itsk1tty.me/Interstellar.mp4 (it's russian)
3.Try to watch it.
Also, it's 1.12.2, mcef is 0.9, wd is 1.0
there's no crash, so there's no crashlogs

**Comment by Teomaniaforreal** [comment]
I already know why, this is a common issue in the newer versions of webdisplays and it's because of the chromium version being used not supporting h264 
That's why most media can't be played and it's been an issue for over a year.

**Comment by ItsK1tty** [comment]
Over a year? And nobody didn't do a fork with h264 codec on?

**Comment by ItsK1tty** [comment]
Also, if not, what does MCEF/WD support? H.265? Mpeg-2? Mpeg-4?

**Comment by ItsK1tty** [comment]
Update: MP4 files with VP8/VP9 codec can be played in WD

**Comment by Teomaniaforreal** [comment]
To fix the issue MCEF should be updated i believe. (https://github.com/montoyo/mcef)
though i do know of a guy that tried updating it: (https://github.com/binary1230/mcef)
but the last release was a year ago so idk. If you know anyone that _could_ update it, ask them pls

**Comment by ItsK1tty** [comment]
I've tried contacting montoyo, but no answer still. However, the best solution for now is:
1. Download format factory (which is most likely gui for ffmpeg)
2. Convert your videofile to .webm with these codecs:
 VP9 codec (for video stream)
Opus codec (for audio stream)
3. Wait until it'll transcode
4.Upload it somewhere (can be played via standard html5 player, dk about other services like vimeo or google drive)
5. Try playing it.
Yesterday watched the martian on WD, looks cool

P.S. I might know the guy who can try to update it, but it might be difficult as he making addon for galacticraft (GalaxySpace)

**Comment by Teomaniaforreal** [comment]
I really want someone to update it because I need this mod for livestreams only, which for now are in H.264 on Youtube and Twitch, meaning none will work, they don't stream in vp9 codec unfortunately.

**Comment by ItsK1tty** [comment]
Uhh, I want to watch twitch in WD too. I'll leave this issue open, so everyone can say something here

**Comment by montoyo** [comment]
Don't know if updating the chromium version will do the job. Chromium is the open-source part of Chrome, and some MP4 codecs (like H264) are not so open. But I'll try.

**Comment by ItsK1tty** [comment]
Uh, yea, they're patented. But Chrome can play it, so Google made Chrome work with it somehow, even if it's not "so open" codec, so it should be somewhere in Chromium source code

**Comment by ItsK1tty** [comment]
Offtopic: Montoyo, why WD had no updates for a year? There should be some minor bugfixes, or something..

**Comment by montoyo** [comment]
Chromium updated. Lemme know if it fixed something...

**Comment by ItsK1tty** [comment]
@montoyo I dont see any new releases for webdisplays tho, only mcef. Is WD 1.0 compatible with MCEF 1.11?

**Comment by ItsK1tty** [comment]
Uh, I see. I've downloaded WD 1.1 and MCEF 1.11 from montoyo.net, but when I go to html5test.com It's permaloading, so I can't check what's supported now

**Comment by montoyo** [comment]
You can't see WD 1.1 ? Might be a cache issue..

**Comment by ItsK1tty** [comment]
I can, I thought it will be on https://github.com/montoyo/webdisplays/releases, but then I went to http://montoyo.net

**Comment by ItsK1tty** [comment]
Also, try this one: http://minecraft.itsk1tty.me/01.avi
It's not working for me

**Comment by montoyo** [comment]
Here is fine. Anyway... after a bit of research, H264 needs to be enabled in the CEF build. The pre-built binaries I'm using do not have H264 enabled, which means I would have to compile CEF myself. As this takes **DAYS** to build (yes, days, and I'm not exaggerating), I won't do it... sorry.

**Comment by ItsK1tty** [comment]
So... we won't get H264 and others, right?

**Comment by montoyo** [comment]
I'm afraid so :/

**Comment by ItsK1tty** [comment]
Eh. What about H265, Mpeg-4?

**Comment by montoyo** [comment]
Audio/video codecs are a mess, and as I said, I don't want to fight to get them working. If you want to help, you can try to build CEF with H264 and whatever you want enabled yourself 😉

Anyway; I'm closing this issue...

**Comment by ItsK1tty** [comment]
Even if I will try to build cef with h264, I couldn't make it work with wd&mcef because of your license

**Comment by montoyo** [comment]
Wrong as MCEF is BSD. Also wtf with the title?

**Comment by ItsK1tty** [comment]
I thought, since we're not talking about MP4 itself, I've decided to rename this issue

**Comment by Magi1053** [comment]
Is there no way to add partial support? I'm trying to create a movie theater with a working livestream for my modpack server and it's very difficult when the only video format supported is VP8 and VP9

**Comment by ItsK1tty** [comment]
@Magi1053 there is, but montoyo got other projects to work on, and, as I said, it will take days to get it work. I'm gonna help him and build cef with  proprietary codecs support, but this will take time

**Comment by ItsK1tty** [comment]
all my attempts building CEF with propreitary codecs have ended with failure. I've got another idea on how to build it, but if it will fail, I'll just surrender. 
@Magi1053, in theory, you could make FFMPEG transcode the livestream to VP9, but it'll require some good computer powers to transcode every second instantly, so if you don't have some powerful Xeons, it would be difficult to transcode the stream.

**Comment by ItsK1tty** [comment]
after a year, I've got back to the cef, and I successfully compiled it with proprietary codecs. The thing is, cef has chromium version 47.

**Comment by StaringWhere** [comment]
@ItsK1tty Finally I can watch twitch in MC, amazing work! May I fork your project, or would you like to give me some guidance on building it myself?

**Comment by ItsK1tty** [comment]
@StaringWhere actually, I think chromium version I compiled is too old for Twitch or YouTube, plus montoyo needs to make changes to MCEF, so we can't use it now even if we wanted to

**Comment by ItsK1tty** [comment]
hey @montoyo can't you just grab already built cef from their website and implement it? why compiling?

**Comment by Seinzen777** [comment]
Hi ! @ItsK1tty Hi. I wish I could contact you. Do you have discord ?

**Comment by ItsK1tty** [comment]
K1tty#2077

**Comment by BoostSK** [comment]
Hello @ItsK1tty. I would like to ask if you got any news? bcs i want to watch livestreams on a webdisplay mod but it doesnt work. Here is my discord. Thank you :)
Boost#6353

**Comment by ItsK1tty** [comment]
back on this lol for 6th time already

**Comment by ItsK1tty** [comment]
> 
> 
> Hello @ItsK1tty. I would like to ask if you got any news? bcs i want to watch livestreams on a webdisplay mod but it doesnt work. Here is my discord. Thank you :)
> Boost#6353

you still need help? i missed your message here

**Comment by kenzo0s1** [comment]
> > Hello @ItsK1tty. I would like to ask if you got any news? bcs i want to watch livestreams on a webdisplay mod but it doesnt work. Here is my discord. Thank you :)
> > Boost#6353
> 
> you still need help? i missed your message here



> > Hello @ItsK1tty. I would like to ask if you got any news? bcs i want to watch livestreams on a webdisplay mod but it doesnt work. Here is my discord. Thank you :)
> > Boost#6353
> 
> you still need help? i missed your message here

help me plz))) ya otpravil zapros v diskorde
I sent a request in discord "qwent"

**Comment by KraemerJoe** [comment]
Hey @ItsK1tty, I'm forking webdisplays with latest chromium version and making on mac os.
I tried to launch it but I need help with the codec, I'm still unable to play videos on twitch etc ( works on youtube classic but not on live) I'm sure it's codec problem.

Can you contact me please on discord ? Jo'#1539

Thanks you !

**Comment by ItsK1tty** [comment]
You have a better chance if you check out [ds58/mcef](https://github.com/ds58/mcef) fork. There are also a few folks on their server who are tinkering MCEF: 
https://discord.gg/x8EuEqZa

**Comment by KraemerJoe** [comment]
> You have a better chance if you check out [ds58/mcef](https://github.com/ds58/mcef) fork. There are also a few folks on their server who are tinkering MCEF: 
> https://discord.gg/x8EuEqZa

Thanks for the answer.
I already contacted cinemamod & it's not working on macos at the moment.
I will check the other repo and try to find their chromium compiled for mac if it works.

**Comment by ItsK1tty** [comment]
FYI, they use bsdiffs: a patch is applied to a  non-proprietary build of CEF to transform it into a proprietary CEF build.

**Comment by KraemerJoe** [comment]
> FYI, they use bsdiffs: a patch is applied to a  non-proprietary build of CEF to transform it into a proprietary CEF build.

Thanks you very much for this info, where did you find it ? It can be usefull
