### ISSUE TITLE
mcef-1.12.2-0.9 needs to be updated to forge-14.23.5.2838

### ISSUE THREAD

**Issue by VanillaChan6571** [montoyo/webdisplays#42]
Crashes and will not start with latest forge.
https://www.pastefs.com/pid/141042 (crash reported)

**Comment by OneSharpAce** [comment]
I would say that your error is a conflict with another mod, I am running just webdisplays on the latest forge with no issues.

**Comment by matboy1** [comment]
> I would say that your error is a conflict with another mod, I am running just webdisplays on the latest forge with no issues.

i got the same thing but i have only this mod what is the name of your mod to be sure i have the same thing of you and the version of your forge

**Comment by montoyo** [comment]
Updated to latest recommended Forge version (14.23.5.2768). Check out WebDisplays 1.1 and MCEF 1.11.
