### ISSUE TITLE
Having to close java in task manager to get server to work

### ISSUE THREAD

**Issue by JasonBourneAxis** [montoyo/webdisplays#43]
My friend runs a modded server using technic on 1.7.10. One issue we have is we can’t load up the mod pack without closing java in task manager otherwise it won’t run. It takes too much time and it causes many issues for the players. How do I fix this?

**Comment by ItsK1tty** [comment]
I think there's no way to fix it, maybe hosting on linux could (haven't tested on technic pack). Until montoyo won't go back to WD or someone fork it, all we have to do is wait. **I think** an update with possible fix will be out soon, as @montoyo promised in #41 that "he'll try" to make an update for WD
Also, I haven't seen that problem before, as I'm running a server on linux with WD on, so it could be problem in technic pack itself

**Comment by JasonBourneAxis** [comment]
It isn't the technic pack. I've spoken to technic admins, they've said this with the logs I've provided

"Looks like author knows, promised a fix, has not done so yet... .has been over a year Also, this modpack was packaged badly

It is over 1GB, and has a TON of things in it you should not be including

It should only have Bin, Mods, Config, and your server.dat. Everything else can go"

**Comment by JasonBourneAxis** [comment]
https://github.com/montoyo/mcef/issues/27 is the issue at hand, it was promised a fix almost a year ago. Nothing happens.

**Comment by ItsK1tty** [comment]
Then, I don't know, sorry. I'm just a regular user as you, so can't do many.

**Comment by montoyo** [comment]
Not touching 1.7.10 again. Sorry.
