### ISSUE TITLE
Will the older versions of Web Displays continue to work like normal after support ends for them? (1.7.10)

### ISSUE THREAD

**Issue by GalaxyKitten42** [montoyo/webdisplays#46]
I understand that this forum is specifically for the newer versions of Web Displays and I've never experienced any real issues with this mod, but I was just wondering. After the support has ended for Web Displays 1.7.10 version, will I still be able to continue and use the web screen like normal? Or will it stop working, as in not being able to turn on and browse the internet anymore because it is no longer being supported? (To be honest, I'm not sure if support has already ended for it or not, I haven't had internet in months). I was just wondering this because 1.7.10 (single player) is literally all I play and I only ever use this mod to watch YouTube videos. I understand after support has ended, current bugs present in the 1.7.10 version will no longer be fixed, and I don't mind that. But I was wondering if the actual web screen will still continue to turn on and work like it always had done in the past. 
https://github.com/montoyo/webdisplays/issues/33#issuecomment-478168834

P.S Sorry, I know this is more of a question rather than an issue.

**Comment by GalaxyKitten42** [comment]
I understand after support has ended, current bugs present in the 1.7.10 will no longer be fixed. But I was wondering if the actual web screen will still continue to turn on and work.

**Comment by ItsK1tty** [comment]
For a while. After some time its chromium version would be too old to play any videos (like WD 1.0 (latest))

**Comment by GalaxyKitten42** [comment]
Does the Chromium version have to be specific to the Minecraft version? For example using the latest MCEF for 1.7.10.

**Comment by ItsK1tty** [comment]
Nope. MCEF(Minecraft Chromium Embedded Framework) uses JCEF (Java Chromium Embedded Framework ) (updated), which is fork of CEF (Chromium Embedded Framework), so all montoyo has to do is copy-paste JCEF to MCEF. Pretty simple.

**Comment by ItsK1tty** [comment]
So it could be any release version of JCEF

**Comment by GalaxyKitten42** [comment]
So, theoretically if I was to update the MCEF version to the newest on the 1.7.10 version, will the web screen continue to work?

**Comment by montoyo** [comment]
> 
> 
> Nope. MCEF(Minecraft Chromium Embedded Framework) uses JCEF (Java Chromium Embedded Framework) (updated), which is java fork of CEF (Chromium Embedded Framework), so all montoyo has to do is copy-paste JCEF to MCEF. Pretty simple.

Yeah... not really. In fact, if it was that easy, it would have been done a long time ago. The thing is, it never works with just a copy/paste. Even the test browser from JCEF doesn't work correctly with off-screen rendering (what is used to embed the browser into Minecraft)... so I have to fix JCEF, then adapt it to work in Minecraft, and then it _might_ work. It results in not so many line of codes, that I can concede. However, it just takes forever...

Anyway... to answer @GalaxyKitten42 yes it will continue to work. Some web-related stuff might not work, but so far everything looks fine (I tested the old version today and had no problem with YouTube videos...)

**Comment by GalaxyKitten42** [comment]
Ah, that is good to hear. Thank you! :)

**Comment by ItsK1tty** [comment]
> > Nope. MCEF(Minecraft Chromium Embedded Framework) uses JCEF (Java Chromium Embedded Framework) (updated), which is java fork of CEF (Chromium Embedded Framework), so all montoyo has to do is copy-paste JCEF to MCEF. Pretty simple.
> 
> Yeah... not really. In fact, if it was that easy, it would have been done a long time ago. The thing is, it never works with just a copy/paste. Even the test browser from JCEF doesn't work correctly with off-screen rendering (what is used to embed the browser into Minecraft)... so I have to fix JCEF, then adapt it to work in Minecraft, and then it _might_ work. It results in not so many line of codes, that I can concede. However, it just takes forever...
> 
> Anyway... to answer @GalaxyKitten42 yes it will continue to work. Some web-related stuff might not work, but so far everything looks fine (I tested the old version today and had no problem with YouTube videos...)

Uh, but you can just copy-paste your commits from mcef source code and adapt it to work with new jcef, isn't it?

**Comment by montoyo** [comment]
Yes. Except for the fact that JCEF updates are not just chromium updates; JCEF itself (so, the java wrapper) has changes. These changes break stuff. And like I said, I need to fix that. You can ask binary1230 about how he struggled to update JCEF himself (https://github.com/montoyo/mcef/pull/31)

**Comment by GalaxyKitten42** [comment]
I have another question (it's slightly silly). Basically I'm upgrading some parts on my PC, such as RAM (8GB to 16GB), and GPU (GTX 460 to GTX 1050). Was wondering if these changes would affect the functionality and/or visuals of this mod?

**Comment by ItsK1tty** [comment]
It will affect in a good side, so there wouldn't be any problems running Web Displays. Internet requirements  - I think 15 mbit/s would be enough for browsing internet
