### ISSUE TITLE
Where is the config?

### ISSUE THREAD

**Issue by Magi1053** [montoyo/webdisplays#47]
I am trying to increase the maximum size of the screens, but I can't seem to find a config file anywhere on my server or client. Alternatively is there a way for admin to override the maximum size when in creative mode?

**Comment by ItsK1tty** [comment]
Look for webdisplays.cfg, make sure you're looking in the right Minecraft directoryI could drop you mine if you want

**Comment by Magi1053** [comment]
I found it, don't know why I didn't see it before 😅

**Comment by Magi1053** [comment]
What is "miniserv"?

**Comment by ItsK1tty** [comment]
Uh, I dont even know. Looks like a mini server, that can do various things

**Comment by montoyo** [comment]
https://montoyo.net/wdwiki/index.php/Server
