### ISSUE TITLE
Video won't autoplay

### ISSUE THREAD

**Issue by Magi1053** [montoyo/webdisplays#48]
I am trying to use this mod to create a movie theater for my private modpack server. I am running into issues with the screen autoplaying using the html 5 video tag with the autoplay attribute. Testing the page in my browser autoplays the video fine, but it does not autoplay in the mod.
I also tried using the javascript plugin https://videojs.com/, and it provided me with the error `NotAllowedError: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD`

**Comment by Magi1053** [comment]
I fixed this by adding `--autoplay-policy=no-user-gesture-required` to S:cefArgs in mcef.cfg

**Comment by montoyo** [comment]
I wonder if that should be the default for WebDisplays...
