### ISSUE TITLE
[Request] Server Side Streaming

### ISSUE THREAD

**Issue by EpicnessTwo** [montoyo/webdisplays#5]
Not too sure if it's possible at all but I'd love this mod to be able to stream the content from a server.

I've had the idea for hosting a Movie Night within Minecraft but this wouldn't work if someone was to leave and rejoin as they'd then be out of sync with everyone else. I'm not worried about power or bandwidth as I've got some fairly powerful servers that could host this.

**Comment by montoyo** [comment]
Streaming is not trivial and would require an enormous amount of work. Sorry, but this is far beyond the scope of WebDisplays, and anyway I don't have time for this 😕. Hope you'll understand :/

What you can do, however, is find some streaming platform on the web, stream your movie and open a WebDisplays browser to that streaming platform.
