### ISSUE TITLE
Multiple issues/suggestions

### ISSUE THREAD

**Issue by josh-65** [montoyo/webdisplays#60]
Answered:
_**1) Youtube live streams don't work i just get this:**_
![2019-11-17_21 24 56](https://user-images.githubusercontent.com/26977075/69014312-cd1e4b80-0980-11ea-93f6-6145ec83931e.png)

Answered:
_**2) Spotify needs Secure playback enabled:**_
![2019-11-17_21 26 50](https://user-images.githubusercontent.com/26977075/69014327-fd65ea00-0980-11ea-8748-715b0f4686ac.png)

3) On Googles sign in, copy and paste doesn't work (I use a password manager. This is annoying) and if i type it will jump to the front or back with certain characters after a certain number of typed characters.

4) There should be a way of turning off the screen.

__Versions:__
Minecraft: 1.12.2
Web displays: 1.1
MEFC: 1.11

**Comment by ItsK1tty** [comment]
#16

**Comment by ItsK1tty** [comment]
Also, as @montoyo said in #41, MCEF needs proprietary codecs built-in, so the only supported codecs are VP8,VP9,Opus, theora, vorbis. I tried compiling CEF with prop. codecs, but after many good tries I just gave up

**Comment by josh-65** [comment]
ok thanks
