### ISSUE TITLE
Bring back ComputerCraft support.

### ISSUE THREAD

**Issue by montoyo** [montoyo/webdisplays#7]
Apparently ComputerCraft is not dead. Gotta add it back!

**Comment by DerSimonYT** [comment]
Where is Computer Craft for 1.12 :O Im searching for it a long time...

**Comment by binary1230** [comment]
@montoyo was going to maybe have a look at doing this for a project I"m working on where I'd like to switch the screen URL from computercraft.   Do you have the code for the older 0.11 webdisplays release somewhere you could upload?  I figured it might be easier to start from where that was working.

If not, any tips on what to do to implement this?

**Comment by binary1230** [comment]
update: see PR #22, barring a bit more testing I think I've added it back in

**Comment by montoyo** [comment]
This is perfect. It's missing forge's Optional annotations, but apart from that everything is fine.
I'm not accepting the PR because of the very closed license (sorry about that... hope you don't mind :S), but I'll make sure to credit you, that's for sure 👍

**Comment by binary1230** [comment]
Sure, glad to help :)

This was my first Minecraft mod stuff and was quite an adventure.  Thanks for all the work on it.   One day I will finish my redstone based AI to finish driving a Kerbal space program rocket and will give you props there

**Comment by montoyo** [comment]
Here we go. Added in the latest release.
