### ISSUE TITLE
Can't play Webm(V9) video

### ISSUE THREAD

**Issue by josh-65** [montoyo/webdisplays#79]
Using htlm5test.com it says Web Displays can use that codec but it doesn't work for me it will display the video box but the just be gray.

**Comment by ItsK1tty** [comment]
can you send a link to that video? I'll check it out if I can do something

**Comment by josh-65** [comment]
Just extra information it a local video file i'm trying to load from the wd_filehost folder
https://drive.google.com/file/d/1T2sFfKGlMN8OIfliPSm2jXxAfgKSYSmU/view?usp=sharing

**Comment by ItsK1tty** [comment]
I'll check it out tomorrow. Been working on some private projects, tired as truck.

**Comment by ItsK1tty** [comment]
![image](https://user-images.githubusercontent.com/45013913/88553798-5caaec80-d02e-11ea-89d1-6147b8d09257.png)

**Comment by josh-65** [comment]
how did you get it to work. did you just put in the file host folder?

**Comment by ItsK1tty** [comment]
nope. just uploaded to my webserver and entered the URL

**Comment by josh-65** [comment]
oh what do you use for the webserver?

**Comment by ItsK1tty** [comment]
[XAMPP](https://www.apachefriends.org/ru/index.html)

**Comment by josh-65** [comment]
Thanks
