### ISSUE TITLE
Game crashes when starting with newest version of 1.12.2 forge

### ISSUE THREAD

**Issue by ItsPapoPlayz** [montoyo/webdisplays#80]
My game will crash instantly when I try to run Forge 1.12.2 with Webdisplays. It crashes during the forge loading screen, which is wierd. I am using the lastest version of 1.12.2 forge. Here is my crash report : https://pastebin.com/MDytHigj The allocated RAM was 4GB

**Comment by ItsK1tty** [comment]
#69
