### ISSUE TITLE
Videos not loading

### ISSUE THREAD

**Issue by DomDar** [montoyo/webdisplays#93]
I recently added this mod to my modpack, and its been working very well except for the fact that only youtube videos load. Maybe I havent been looking hard enough, but I've looked for other people with this issue and I cant find a concrete answer on if its possible or not. Is there a way to tweak it to allow support for other video types?

**Comment by BigMan1231** [comment]
WebDisplays doesn't support stuff like that cause of video codecs, idk much about them but ik WD can only run open google ones like vp8 and vp9. Other sites like twitch and netflix and most streaming services use h265, h264 and aac. They are the default for .mp4, which is like the most popular video file. So only youtube really works. A work around would probably be downloading what your trying to watch, make a .webm/other video file, and just upload it somewhere that wont have it taken down. (because u know copyright) I dont know a ton about codecs and stuff but that is my best answer.

**Comment by ItsK1tty** [comment]
Yeah, @BigMan1231's answer is good enough. If you want to watch something that isn't a YouTube video, you will have to transcode it to open codecs. I use ffmpeg to transcode streams and movies to watch with my friends in the Minecraft cinema powered by WD.

**Comment by DomDar** [comment]
Got it, I will try this out, thank you for the help

**Comment by ItsK1tty** [comment]
Oh, and another thing, you need processing power for transcoding. Personally, I overclocked my CPU to 5GHz to transcode as fast as it could, as I don't really like waiting, so if you will also tweak your hardware, make sure you got good cooling.

**Comment by DomDar** [comment]
Where would you recommend uploading the video to?

**Comment by DomDar** [comment]
Would google drive work?

**Comment by ItsK1tty** [comment]
I don't know about google drive, but it should do. I host the output through the webserver to have direct interaction with browser (WD) and my server without any underwater stones from Google.

**Comment by DomDar** [comment]
Does that work in multiplayer? Cuz I know there's issues with synchronization between people

**Comment by ItsK1tty** [comment]
There's no sync between players, so you have to have your friends ready with popcorn and start the show when they all are up

**Comment by LazerSharkGaming** [comment]
> Yeah, @BigMan1231's answer is good enough. If you want to watch something that isn't a YouTube video, you will have to transcode it to open codecs. I use ffmpeg to transcode streams and movies to watch with my friends in the Minecraft cinema powered by WD.

Can you do a small guide on transcoding?

**Comment by ItsK1tty** [comment]
Video or text?

**Comment by A-Pedraja** [comment]
I would really apprecciate if someone can make a tutorial, on how to do this :(

> Yeah, @BigMan1231's answer is good enough. If you want to watch something that isn't a YouTube video, you will have to transcode it to open codecs. I use ffmpeg to transcode streams and movies to watch with my friends in the Minecraft cinema powered by WD.
