### ISSUE TITLE
Does the Web Displays mod require adobe flash (for YouTube videos)?

### ISSUE THREAD

**Issue by GalaxyKitten42** [montoyo/webdisplays#94]
First and foremost, I am a big fan of this mod (I have it installed on my 1.7.10 modpack, to which I still play to this day). Though I was wondering if this mod (most specifically YouTube videos) would still work? Because as of recently Adobe Flash Player was discontinued and I am not sure if that is in any way shape or form required for this mod in order for it to work (and for me to watch youtube videos on)? I haven't been on my PC for a while so I haven't really tested it out since but I was just wondering if this mod still works after the discontinuation of Adobe Flash Player? And this applies for all versions of the mod (most specifically 1.7.10).

P.S sorry that this was more of a question rather than an actual issue.

**Comment by ItsK1tty** [comment]
Short answer: yes, it still will work
How to check to be 420% sure:
-Uninstall Flash player
-Play a video on YouTube
Profit!

**Comment by GalaxyKitten42** [comment]
Ah thanks! To be honest, I don't think I even have Flash Player installed anyway lol

**Comment by NLferdiNL** [comment]
YouTube hasn't used Flash in years. It's all HTML5 now. Which most modern browsers (and this mod uses Chromium) support. You're good. And Flash is getting dumped this year, Chrome has already done so.
